# 一般設定

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1


[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

# python設定

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo='tell-k/vim-autopep8'
on_ft ='python'

#ruby
#
[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = 'ruby'

[[plugins]]
repo = 'marcus/rsense'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'
on_ft = 'ruby'
on_i = 1

#go
[[plugins]]
repo='fatih/vim-go'
on_ft='go'

[[plugins]]
repo='nsf/gocode'
on_ft='go'

# C/C++
[[plugins]]
repository = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
