# python設定

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
ok_add = '''
let g:jedi#use_tabs_not_buffers = 1 #補完で次の候補に進むときにtabを使えるという設定にしたつもりですができませんでした。
let g:jedi#popup_select_first = 0 #1個目の候補が入力されるっていう設定を解除
let g:jedi#popup_on_dot = 0 # .を入力すると補完が始まるという設定を解除
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#rename_command = "<leader>R" #quick-runと競合しないように大文字Rに変更. READMEだと<leader>r
'''

#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = 'davidhalter/jedi-vim'
#on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

# 一般設定

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = 'python'
hook_add = 'let g:syntastic_python_checkers = ["flake8","pep8"]'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = 'ruby'

[[plugins]]
repo = 'marcus/rsense'
on_ft = 'ruby'
